# Generated by Django 5.1.3 on 2024-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('user_type', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=25)),
            ],
        ),
    ]
