# Generated by Django 5.1.3 on 2024-11-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
